# ูู ุจุชุบููุฑ ูุฐู ุฃููุงู
owner: info-devf5r # ุงุณู ูุณุชุฎุฏู GitHub ุงูุฎุงุต ุจู ุ ุญูุซ ููุฌุฏ ูุฐุง ุงููุณุชูุฏุน
repo: VPN # ุงุณู ูุฐุง ุงููุณุชูุฏุน

sites:
  - name: ุงููููุน ุงูุฑุณูู
    url: https://devf5r.com
  - name: ูููุน ุจุฏูู
    url: https://almgro7al3nzy.com
  - name: ูููุน ูุฎุฑ ุงู ุจู ุงู
    url: http://api.devf5r.com
  - name: ุชูู ุชูู
    url: https://vt.tiktok.com/ZS8w6nu9M
  - name: ๐ณ๐ฑ ูููููููุฏุง ุณูุฑูุฑ ูุช
    url: http://lu.howdyvpn.com
  - name: ุชุฑููุง ุณูุฑูุฑ ูุช ๐น๐ท
    url: http://tr.vpn.devf5r.com
  - name: ูุฑูุณุง ุณูุฑูุฑ ูุช ๐จ๐ต
    url: http://fr.vpn.devf5r.com
  - name: ูููุน ุฏุฑุฏุดุฉ ูุฎุฑ
    url: https://chat.devf5r.com
  - name: ุชุญุฏูุซ ุงููุงุชุณ ุงุจ
    url: https://update.devf5r.com
  - name: ุจุนุซุฑุฉ ููุงู
    url: https://kalam.devf5r.com
  - name: ุจูุญ ุงููุดุงุนุฑ
    url: https://quotes.devf5r.com
  - name: ุฑูุน ุงููููุงุช
    url: https://up.devf5r.com
  - name: ูููุน ูู ุจู ุงู
    url: https://vpn.devf5r.com

status-website:
  # ุฃุถู ุงุณู ุงููุฌุงู ุงููุฎุตุต ุงูุฎุงุต ุจู ุ ุฃู ูู ุจุฅุฒุงูุฉ ุณุทุฑ `cname` ุฅุฐุง ูู ููู ูุฏูู ูุฌุงู
  # ูู ุจุฅูุบุงุก ุงูุชุนููู ุนู ุณุทุฑ "baseUrl" ุฅุฐุง ูู ููู ูุฏูู ูุฌุงู ูุฎุตุต ูุฃุถู ุงุณู ุงูุฑูุจู ุงูุฎุงุต ุจู ููุงู
  #cname: info-devf5r.github.io/VPN
  baseUrl: /VPN
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: VPN
  introTitle: "** VPN ** ูู ุตูุญุฉ ุงูุญุงูุฉ ููุฑุงูุจุฉ ููุช ุงูุชุดุบูู ููุชูุญุฉ ุงููุตุฏุฑ ุ ููู ูุฏุนููุฉ ุจุงููุงูู ุจูุงุณุทุฉ GitHub."
  introMessage: ูุฐู ูููุฐุฌ ูุตูุญุฉ ุงูุญุงูุฉ ุงูุชู ุชุณุชุฎุฏู ุจูุงูุงุช ** ูู ุงูููุช ุงููุนูู ** ูู [ูุณุชูุฏุน GitHub] (https://devf5r.com). ูุง ููุฒู ูุฌูุฏ ุฎุงุฏู - ููุท ุฅุฌุฑุงุกุงุช GitHub ูุงููุดููุงุช ูุงูุตูุญุงุช. [** ุงุญุตู ุนูู ูุง ูุฏูู ูุฌุงููุง **] (https://devf5r.com)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# ูุฏุนู Upptime ุฃูุถูุง ุงูุฅุดุนุงุฑุงุช ูุชุนููู ุงููุดููุงุช ูุงููุฒูุฏ
# See https://upptime.js.org/docs/configuration
