owner: info-devf5r
repo: VPN

sites:
  - name: Official Website
    url: https://devf5r.com
  - name: alternative site
    url: https://almgro7al3nzy.com
  - name: API Website
    url: http://api.devf5r.com
  - name: Tik Tok
    url: https://vt.tiktok.com/ZS8w6nu9M
  - name: CHAT Website
    url: https://chat.devf5r.com
  - name: WhatsApp update
    url: https://update.devf5r.com
  - name: slurred speech
    url: https://kalam.devf5r.com
  - name: The spirit of feelings
    url: https://quotes.devf5r.com
  - name: upload files
    url: https://up.devf5r.com
    
  - name: Private server net site 🇪🇺
    url: https://vpn.devf5r.com
  - name: 🇳🇱 Netherlands Server Net
    url: http://nl.vpn.devf5r.com
  - name: 🇳🇱 2 Netherlands Server Net
    url: http://nlt-1.vpn.devf5r.com
  - name: Türkiye Server Net 🇹🇷
    url: http://tr.vpn.devf5r.com
  - name: France Server Net 🇨🇵
    url: http://fr.vpn.devf5r.com
  - name: 🇳🇱 Luxenburg Server Net
    url: http://lu.vpn.devf5r.com
  - name: Germany Server Net 🇩🇪
    url: http://de-1.vpn.devf5r.com
    
    
status-website:
  baseUrl: /VPN
  logoUrl: http://assets.devf5r.com/LOGO-AK.png
  name: VPN Pro
  introTitle: "** VPN ** هي صفحة الحالة ومراقبة وقت التشغيل مفتوحة المصدر ، وهي مدعومة بالكامل بواسطة"
  introMessage: هذه نموذج لصفحة الفعلي ** من . لا يلزم وجود خادم - فقط إجراءات  والمشكلات والصفحات. [****] (https://devf5r.com)
  navbar:
    - title: Home
      href: https://info-devf5r.github.io/VPN
    - title: Dev F5R
      href: https://devf5r.com
    - title: AKWT
      href: https://up.devf5r.com
    - title: CHAT
      href: https://chat.devf5r.com




