# قم بتغيير هذه أولاً
owner: info-devf5r # اسم مستخدم GitHub الخاص بك ، حيث يوجد هذا المستودع
repo: VPN # اسم هذا المستودع

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: موقع فخر لايف
    url: https://live.devf5r.com
  - name: موقع فخر اي بي اي
    url: http://api.devf5r.com
  - name: موقع تجريبي
    url: https://www.nulled.to
  - name: سيرفر نت بريطاني
    url: http://uk.vpn.devf5r.com
  - name: سيرفر نت تركي
    url: http://tr.vpn.devf5r.com
  - name: سيرفر نت فرنسي
    url: http://fr.vpn.devf5r.com
  - name: الموقع الرسمي
    url: https://devf5r.com
  - name: موقع دردشة فخر
    url: https://chat.devf5r.com
  - name: تحديث الواتس اب
    url: https://update.devf5r.com
  - name: بعثرة كلام
    url: https://kalam.devf5r.com
  - name: بوح المشاعر
    url: https://quotes.devf5r.com
  - name: رفع الملفات
    url: https://up.devf5r.com
  - name: موقع في بي ان
    url: https://vpn.devf5r.com

status-website:
  # أضف اسم المجال المخصص الخاص بك ، أو قم بإزالة سطر `cname` إذا لم يكن لديك مجال
  # قم بإلغاء التعليق عن سطر "baseUrl" إذا لم يكن لديك مجال مخصص وأضف اسم الريبو الخاص بك هناك
  #cname: info-devf5r.github.io/VPN
  baseUrl: /VPN
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: VPN
  introTitle: "** VPN ** هي صفحة الحالة ومراقبة وقت التشغيل مفتوحة المصدر ، وهي مدعومة بالكامل بواسطة GitHub."
  introMessage: هذه نموذج لصفحة الحالة التي تستخدم بيانات ** في الوقت الفعلي ** من [مستودع GitHub] (https://devf5r.com). لا يلزم وجود خادم - فقط إجراءات GitHub والمشكلات والصفحات. [** احصل على ما لديك مجانًا **] (https://devf5r.com)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# يدعم Upptime أيضًا الإشعارات وتعيين المشكلات والمزيد
# See https://upptime.js.org/docs/configuration
