# ูู ุจุชุบููุฑ ูุฐู ุฃููุงู
owner: info-devf5r # ุงุณู ูุณุชุฎุฏู GitHub ุงูุฎุงุต ุจู ุ ุญูุซ ููุฌุฏ ูุฐุง ุงููุณุชูุฏุน
repo: VPN # ุงุณู ูุฐุง ุงููุณุชูุฏุน

sites:
  - name: ุงููููุน ุงูุฑุณูู
    url: https://devf5r.com
  - name: ูููุน ุจุฏูู
    url: https://almgro7al3nzy.com
  - name: ูููุน ูุฎุฑ ุงู ุจู ุงู
    url: http://api.devf5r.com
  - name: ุชูู ุชูู
    url: https://vt.tiktok.com/ZS8w6nu9M
  - name: ูููุน ุฏุฑุฏุดุฉ ูุฎุฑ
    url: https://chat.devf5r.com
  - name: ุชุญุฏูุซ ุงููุงุชุณ ุงุจ
    url: https://update.devf5r.com
  - name: ุจุนุซุฑุฉ ููุงู
    url: https://kalam.devf5r.com
  - name: ุจูุญ ุงููุดุงุนุฑ
    url: https://quotes.devf5r.com
  - name: ุฑูุน ุงููููุงุช
    url: https://up.devf5r.com
    
  - name: ูููุน ุณูุฑูุฑ ูุช ุฎุงุต ๐ช๐บ
    url: https://vpn.devf5r.com
  - name: ๐ณ๐ฑ ูููููููุฏุง ุณูุฑูุฑ ูุช
    url: http://nl.vpn.devf5r.com
  - name: ๐ณ๐ฑ 2ูููููููุฏุง ุณูุฑูุฑ ูุช
    url: http://nlt-1.vpn.devf5r.com
  - name: ุชุฑููุง ุณูุฑูุฑ ูุช ๐น๐ท
    url: http://tr.vpn.devf5r.com
  - name: ูุฑูุณุง ุณูุฑูุฑ ูุช ๐จ๐ต
    url: http://fr.vpn.devf5r.com
  - name: ๐ณ๐ฑ ูููุณูุจูุฑุบ ุณูุฑูุฑ ูุช
    url: http://lu.vpn.devf5r.com
  - name: ุงููุงููุง ุณูุฑูุฑ ูุช ๐ฉ๐ช
    url: http://de-1.vpn.devf5r.com
    
    
status-website:
  # ุฃุถู ุงุณู ุงููุฌุงู ุงููุฎุตุต ุงูุฎุงุต ุจู ุ ุฃู ูู ุจุฅุฒุงูุฉ ุณุทุฑ `cname` ุฅุฐุง ูู ููู ูุฏูู ูุฌุงู
  # ูู ุจุฅูุบุงุก ุงูุชุนููู ุนู ุณุทุฑ "baseUrl" ุฅุฐุง ูู ููู ูุฏูู ูุฌุงู ูุฎุตุต ูุฃุถู ุงุณู ุงูุฑูุจู ุงูุฎุงุต ุจู ููุงู
  #cname: info-devf5r.github.io/VPN
  baseUrl: /VPN
  logoUrl: http://assets.devf5r.com/LOGO-AK.png
  name: VPN Pro
  introTitle: "** VPN ** ูู ุตูุญุฉ ุงูุญุงูุฉ ููุฑุงูุจุฉ ููุช ุงูุชุดุบูู ููุชูุญุฉ ุงููุตุฏุฑ ุ ููู ูุฏุนููุฉ ุจุงููุงูู ุจูุงุณุทุฉ"
  introMessage: ูุฐู ูููุฐุฌ ูุตูุญุฉ ุงููุนูู ** ูู . ูุง ููุฒู ูุฌูุฏ ุฎุงุฏู - ููุท ุฅุฌุฑุงุกุงุช  ูุงููุดููุงุช ูุงูุตูุญุงุช. [****] (https://devf5r.com)
  navbar:
    - title: Home
      href: https://info-devf5r.github.io/VPN
    - title: Dev F5R
      href: https://devf5r.com
    - title: AKWT
      href: https://up.devf5r.com
    - title: CHAT
      href: https://chat.devf5r.com




